import { Listing } from "@/components/listing-card"

export const sampleListings: Listing[] = [
  {
    id: "1",
    title: "Crushed Plastic Bottles",
    wasteType: "Plastic",
    quantity: "500 kg",
    location: "Lagos, Nigeria",
    price: "₦75,000",
    image: "/images/plastic-bottles.jpg",
  },
  {
    id: "2",
    title: "Mixed Scrap Metal",
    wasteType: "Metal",
    quantity: "1,200 kg",
    location: "Abuja, Nigeria",
    price: "₦320,000",
    image: "/images/scrap-metal.jpg",
  },
  {
    id: "3",
    title: "Recycled Paper & Cardboard",
    wasteType: "Paper",
    quantity: "800 kg",
    location: "Port Harcourt, Nigeria",
    price: "₦45,000",
    image: "/images/paper-waste.jpg",
  },
  {
    id: "4",
    title: "Sorted Glass Bottles",
    wasteType: "Glass",
    quantity: "350 kg",
    location: "Kano, Nigeria",
    price: "₦52,000",
    image: "/images/glass-waste.jpg",
  },
  {
    id: "5",
    title: "Electronic Circuit Boards",
    wasteType: "E-Waste",
    quantity: "100 kg",
    location: "Ibadan, Nigeria",
    price: "₦180,000",
    image: "/images/e-waste.jpg",
  },
  {
    id: "6",
    title: "Used Rubber Tires",
    wasteType: "Rubber",
    quantity: "200 units",
    location: "Enugu, Nigeria",
    price: "₦95,000",
    image: "/images/rubber-waste.jpg",
  },
  {
    id: "7",
    title: "Textile Fabric Offcuts",
    wasteType: "Textile",
    quantity: "600 kg",
    location: "Onitsha, Nigeria",
    price: "₦38,000",
    image: "/images/textile-waste.jpg",
  },
  {
    id: "8",
    title: "Clear PET Bottles",
    wasteType: "Plastic",
    quantity: "750 kg",
    location: "Benin City, Nigeria",
    price: "₦110,000",
    image: "/images/plastic-bottles.jpg",
  },
]
